# Tibouchina Discipline
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 16, 23]  # You can specify multiple Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./  # Pointing to the root directory where package.json is located

      - name: Run tests
        run: npm test
        working-directory: ./tests  # Change to the tests directory
