# Tibouchina Discipline
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 17, 18, 19, 20, 21, 22, 23]  # You can specify multiple Node.js versions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker availability
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed or not available in the PATH."
            exit 1
          else
            echo "Docker is available."
            docker --version
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: user/app:latest

      - name: Install dependencies
        run: npm install
        working-directory: ./  # Pointing to the root directory where package.json is located

      - name: Run tests
        run: npm test
        working-directory: ./tests  # Change to the tests directory

      - name: Run Tests (Optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          docker run --rm thaumaturgists/canamus:latest npm test

      - name: Run Tests (Optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          docker run --rm thaumaturgists/canamus:latest npm test
